version: "3"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    command: npm run dev
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    command: python backend/manage.py runserver 0.0.0.0:8000
    links:
      - db:db
    tty: true
    stdin_open: true
  db:
    build: ./db
    volumes:
      - ./db/datadir:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev_nuxt_django_pw
      - MYSQL_DATABASE=dev_nuxt_django_db
